# Generated by Django 4.2.10 on 2026-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecaestoque',
            name='quantidade_reservada',
            field=models.IntegerField(default=0),
        ),
    ]
