sonar.projectKey=Bondezan_POSTECH-DB
sonar.projectName=POSTECH-DB
sonar.projectVersion=1.0
sonar.organization=fiap-4gl
sonar.projectBaseDir=.
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.tests=accounts,cadastros,estoque,so
sonar.test.inclusions=**/tests.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/*.pyc
