# Generated by Django 4.2.10 on 2026-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('Recebida', 'Recebida'), ('EmDiagnostico', 'Em diagnóstico'), ('AguardandoAprovacao', 'Aguardando aprovação'), ('EmExecucao', 'Em execução'), ('Finalizada', 'Finalizada'), ('Entregue', 'Entregue')], default='Recebida', max_length=30),
        ),
    ]
