# Generated by Django 4.2.10 on 2026-08-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0002_alter_ordemservico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='responsavel',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
    ]
